from .agent import TIRProverAgent
from .config import TIRProverConfig, TIRProverResult
from .prompts import (
    DEFAULT_TIR_PROVER_SYSTEM_PROMPT,
    DEFAULT_TIR_PROVER_LEAN_TOOL_DESCRIPTION,
    DEFAULT_TIR_PROVER_PYTHON_TOOL_DESCRIPTION,
    INFORMAL_PROOF_SYSTEM_ADDENDUM,
    INITIAL_USER_MESSAGE,
    INITIAL_USER_MESSAGE_WITH_INFORMAL_PROOF,
)

__all__ = [
    "TIRProverConfig",
    "TIRProverResult",
    "TIRProverAgent",
    "DEFAULT_TIR_PROVER_SYSTEM_PROMPT",
    "DEFAULT_TIR_PROVER_LEAN_TOOL_DESCRIPTION",
    "DEFAULT_TIR_PROVER_PYTHON_TOOL_DESCRIPTION",
    "INFORMAL_PROOF_SYSTEM_ADDENDUM",
    "INITIAL_USER_MESSAGE",
    "INITIAL_USER_MESSAGE_WITH_INFORMAL_PROOF",
]
